InspectionType.delete_all
[
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Location / Footing / Steel'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Underground Plumbing'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Underground Electrical'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Slab'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Floor Joist'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Floor Insulation'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Floor Sheathing', comments: 'Note floor designation (e.g. 1st, 2nd, 3rd) in comments below, if applicable.'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Roof Sheathing'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Shear Walls Interior / Exterior', comments: 'Note floor designation (e.g. 1st, 2nd, 3rd) in comments below, if applicable.'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Weatherproofing Roof / Walls'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Rough Electrical'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Rough Mechanical'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Rough Plumbing'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Rough Hydro for Fire Sprinkler System'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Framing'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Insulation / Energy'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Drywall'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Lath', comments: 'No scratch / brown coat inspection required.'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Gas Test'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Electrical Final'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Plumbing Final'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Mechanical Final'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Fire Final'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Planning Final'},
  {supercategory: 'residential', category: 'remodel_addition_new', name: 'Building Final'},
  {supercategory: 'residential', category: 'roof', name: 'Pre-cover / Tear Off'},
  {supercategory: 'residential', category: 'roof', name: 'Final'},
  {supercategory: 'residential', category: 'window_replacement', name: 'Framing'},
  {supercategory: 'residential', category: 'window_replacement', name: 'Weatherproofing / Lath'},
  {supercategory: 'residential', category: 'window_replacement', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'window_replacement', name: 'Final'},
  {supercategory: 'residential', category: 'block_wall', name: 'Location / Footing /Steel'},
  {supercategory: 'residential', category: 'block_wall', name: 'Pre-grout', comments: 'Note lift designation (e.g. mid-height, top course) in comments below, if applicable.'},
  {supercategory: 'residential', category: 'block_wall', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'block_wall', name: 'Final'},
  {supercategory: 'residential', category: 'pool', name: 'Location / Steel'},
  {supercategory: 'residential', category: 'pool', name: 'Underground Plumbing'},
  {supercategory: 'residential', category: 'pool', name: 'Underground Electrical'},
  {supercategory: 'residential', category: 'pool', name: 'Gas Test'},
  {supercategory: 'residential', category: 'pool', name: 'Pre-gunite'},
  {supercategory: 'residential', category: 'pool', name: 'Fences / Gates'},
  {supercategory: 'residential', category: 'pool', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'pool', name: 'Electrical Final'},
  {supercategory: 'residential', category: 'pool', name: 'Planning Final'},
  {supercategory: 'residential', category: 'pool', name: 'Mechanical Final'},
  {supercategory: 'residential', category: 'pool', name: 'Pool Final'},
  {supercategory: 'residential', category: 'photovoltaic', name: 'Final'},
  {supercategory: 'residential', category: 'sandblast', name: 'Final'},
  {supercategory: 'residential', category: 'mechanical', name: 'Rough Heating / Air Conditioning'},
  {supercategory: 'residential', category: 'mechanical', name: 'Wall Furnace'},
  {supercategory: 'residential', category: 'mechanical', name: 'Exhaust Fans'},
  {supercategory: 'residential', category: 'mechanical', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'mechanical', name: 'Final'},
  {supercategory: 'residential', category: 'electrical', name: 'Temporary Pole Power'},
  {supercategory: 'residential', category: 'electrical', name: 'Underground Work'},
  {supercategory: 'residential', category: 'electrical', name: 'Rough'},
  {supercategory: 'residential', category: 'electrical', name: 'Energy'},
  {supercategory: 'residential', category: 'electrical', name: 'Electrical Release'},
  {supercategory: 'residential', category: 'electrical', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'electrical', name: 'Final'},
  {supercategory: 'residential', category: 'plumbing', name: 'Underground Work'},
  {supercategory: 'residential', category: 'plumbing', name: 'Rough'},
  {supercategory: 'residential', category: 'plumbing', name: 'Water Heater'},
  {supercategory: 'residential', category: 'plumbing', name: 'Water Distribution / Re-pipe'},
  {supercategory: 'residential', category: 'plumbing', name: 'Water Service'},
  {supercategory: 'residential', category: 'plumbing', name: 'Sewer / Cap'},
  {supercategory: 'residential', category: 'plumbing', name: 'Shower Pan / Tub'},
  {supercategory: 'residential', category: 'plumbing', name: 'Gas Test'},
  {supercategory: 'residential', category: 'plumbing', name: 'Gas Release'},
  {supercategory: 'residential', category: 'plumbing', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'residential', category: 'plumbing', name: 'Final'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Demolition'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Pre-construction'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Site Grading / Soils'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Shoring'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Location / Footing / Steel'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Disabled Access'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Slab'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Floor Joist'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Floor Sheathing'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Roof Sheathing'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Shear Walls Interior / Exterior'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Weatherproofing Roof / Walls'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Framing'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Insulation / Energy'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Drywall'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'T-Bar'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Lath', comments: 'No scratch / brown coat inspection required.'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Planning Final'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Preliminary Building Final', comments: 'Request when seeking a Temporary Certificate of Occupancy'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Preliminary Building Fire Final', comments: 'Request when seeking a Temporary Certificate of Occupancy'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Building Fire Final'},
  {supercategory: 'commercial', category: 'improvements_additions_new', name: 'Building Final'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Rough Heating / Air Conditioning'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Kitchen Hood'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Walk-in-Cooler'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Registers'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Exhaust Fans'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Smoke Control / Dampers'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy'},
  {supercategory: 'commercial', category: 'mechanical', name: 'Final'},
  {supercategory: 'commercial', category: 'electrical', name: 'Temporary Pole Power'},
  {supercategory: 'commercial', category: 'electrical', name: 'Underground Work'},
  {supercategory: 'commercial', category: 'electrical', name: 'Rough'},
  {supercategory: 'commercial', category: 'electrical', name: 'Rough Walls'},
  {supercategory: 'commercial', category: 'electrical', name: 'Rough – Fire / Life Safety'},
  {supercategory: 'commercial', category: 'electrical', name: 'Energy'},
  {supercategory: 'commercial', category: 'electrical', name: 'Electrical Release'},
  {supercategory: 'commercial', category: 'electrical', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'electrical', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy'},
  {supercategory: 'commercial', category: 'electrical', name: 'Final'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Underground Work'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Rough'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Water Heater'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Water Distribution / Re-pipe'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Water Service'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Sewer / Cap'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Shower Pan / Tub'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Gas Test'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Gas Release'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy'},
  {supercategory: 'commercial', category: 'plumbing', name: 'Final'},
  {supercategory: 'commercial', category: 'fire', name: 'Alarm'},
  {supercategory: 'commercial', category: 'fire', name: 'Sprinkler'},
  {supercategory: 'commercial', category: 'fire', name: 'Hood / Suppression'},
  {supercategory: 'commercial', category: 'fire', name: 'Damper'},
  {supercategory: 'commercial', category: 'fire', name: 'Smoke Control'},
  {supercategory: 'commercial', category: 'fire', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy'},
  {supercategory: 'commercial', category: 'fire', name: 'Final'},
  {supercategory: 'commercial', category: 'roof', name: 'Pre-cover / Tear Off'},
  {supercategory: 'commercial', category: 'roof', name: 'Final'},
  {supercategory: 'commercial', category: 'window_replacement', name: 'Framing'},
  {supercategory: 'commercial', category: 'window_replacement', name: 'Weatherproofing / Lath'},
  {supercategory: 'commercial', category: 'window_replacement', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'window_replacement', name: 'Final'},
  {supercategory: 'commercial', category: 'block_wall', name: 'Location / Footing /Steel'},
  {supercategory: 'commercial', category: 'block_wall', name: 'Pre-grout', comments: 'Note lift designation (e.g. mid-height, top course) in comments below, if applicable.'},
  {supercategory: 'commercial', category: 'block_wall', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'block_wall', name: 'Final'},
  {supercategory: 'commercial', category: 'pool', name: 'Location / Steel'},
  {supercategory: 'commercial', category: 'pool', name: 'Underground Plumbing'},
  {supercategory: 'commercial', category: 'pool', name: 'Underground Electrical'},
  {supercategory: 'commercial', category: 'pool', name: 'Gas Test'},
  {supercategory: 'commercial', category: 'pool', name: 'Pre-gunite'},
  {supercategory: 'commercial', category: 'pool', name: 'Fences / Gates'},
  {supercategory: 'commercial', category: 'pool', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'pool', name: 'Health Final'},
  {supercategory: 'commercial', category: 'pool', name: 'Electrical Final'},
  {supercategory: 'commercial', category: 'pool', name: 'Planning Final'},
  {supercategory: 'commercial', category: 'pool', name: 'Mechanical Final'},
  {supercategory: 'commercial', category: 'pool', name: 'Pool Final'},
  {supercategory: 'commercial', category: 'photovoltaic', name: 'Array Attachment'},
  {supercategory: 'commercial', category: 'photovoltaic', name: 'Rough'},
  {supercategory: 'commercial', category: 'photovoltaic', name: 'Release'},
  {supercategory: 'commercial', category: 'photovoltaic', name: 'Final'},
  {supercategory: 'commercial', category: 'sign', name: 'Location / Footing / Steel'},
  {supercategory: 'commercial', category: 'sign', name: 'Underground Conduit'},
  {supercategory: 'commercial', category: 'sign', name: 'Rough'},
  {supercategory: 'commercial', category: 'sign', name: 'Final'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Location / Footing / Steel'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Framing / Attachments'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Rough'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Other', comments: 'Please write in comments section below'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Planning Final'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Fire Final'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Electrical Release'},
  {supercategory: 'commercial', category: 'cell_sites', name: 'Building Final'},
].each do |it|
  InspectionType.create(
    inspection_supercategory: it[:supercategory],
    inspection_category: it[:category],
    inspection_name: it[:name],
    comments: it[:comments],
  )
end

Inspection.delete_all

# today
5.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    requested_for_date: Date.today,
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    notes: Faker::Lorem.sentence,
  )
end

# tomorrow
5.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    requested_for_date: Date.tomorrow,
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    notes: Faker::Lorem.sentence,
  )
end

# future
5.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    requested_for_date: Faker::Date.forward(30),
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    notes: Faker::Lorem.sentence,
  )
end
