InspectionType.delete_all
[
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Location / Footing / Steel' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Underground Plumbing' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Underground Electrical' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Slab' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Floor Joist' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Floor Insulation' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Floor Sheathing', comments: 'Note floor designation (e.g. 1st, 2nd, 3rd) in comments below, if applicable.' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Roof Sheathing' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Shear Walls Interior / Exterior', comments: 'Note floor designation (e.g. 1st, 2nd, 3rd) in comments below, if applicable.' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Weatherproofing Roof / Walls' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Rough Electrical' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Rough Mechanical' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Rough Plumbing' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Rough Hydro for Fire Sprinkler System' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Framing' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Insulation / Energy' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Drywall' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Lath', comments: 'No scratch / brown coat inspection required.' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Gas Test' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Electrical Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Plumbing Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Mechanical Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Fire Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Planning Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'remodel_addition_new', category_name: 'Remodel / Addition / New', name: 'Building Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'roof', category_name: 'Roof', name: 'Pre-cover / Tear Off' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'roof', category_name: 'Roof', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'roof', category_name: 'Roof', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'window_replacement', category_name: 'Window Replacement', name: 'Framing' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'window_replacement', category_name: 'Window Replacement', name: 'Weatherproofing / Lath' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'window_replacement', category_name: 'Window Replacement', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'window_replacement', category_name: 'Window Replacement', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'block_wall', category_name: 'Block Wall', name: 'Location / Footing /Steel' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'block_wall', category_name: 'Block Wall', name: 'Pre-grout', comments: 'Note lift designation (e.g. mid-height, top course) in comments below, if applicable.' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'block_wall', category_name: 'Block Wall', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'block_wall', category_name: 'Block Wall', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Location / Steel' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Underground Plumbing' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Underground Electrical' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Gas Test' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Pre-gunite' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Fences / Gates' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Electrical Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Planning Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Mechanical Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'pool', category_name: 'Pool', name: 'Pool Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'sandblast', category_name: 'Sandblast', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'sandblast', category_name: 'Sandblast', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'mechanical', category_name: 'Mechanical', name: 'Rough Heating / Air Conditioning' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'mechanical', category_name: 'Mechanical', name: 'Wall Furnace' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'mechanical', category_name: 'Mechanical', name: 'Exhaust Fans' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'mechanical', category_name: 'Mechanical', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'mechanical', category_name: 'Mechanical', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Temporary Pole Power' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Underground Work' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Rough' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Energy' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Electrical Release' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'electrical', category_name: 'Electrical', name: 'Final' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Underground Work' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Rough' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Water Heater' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Water Distribution / Re-pipe' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Water Service' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Sewer / Cap' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Shower Pan / Tub' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Gas Test' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Gas Release' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'residential', supercategory_name:'Single-family / Duplex', category: 'plumbing', category_name: 'Plumbing', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Demolition' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Pre-construction' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Site Grading / Soils' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Shoring' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Location / Footing / Steel' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Disabled Access' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Slab' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Floor Joist' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Floor Sheathing' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Roof Sheathing' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Shear Walls Interior / Exterior' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Weatherproofing Roof / Walls' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Framing' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Insulation / Energy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Drywall' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'T-Bar' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Lath', comments: 'No scratch / brown coat inspection required.' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Planning Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Preliminary Building Final', comments: 'Request when seeking a Temporary Certificate of Occupancy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Preliminary Building Fire Final', comments: 'Request when seeking a Temporary Certificate of Occupancy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Building Fire Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'improvements_additions_new', category_name: 'Tenant Improvements / Additions / New', name: 'Building Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Rough Heating / Air Conditioning' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Kitchen Hood' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Walk-in-Cooler' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Registers' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Exhaust Fans' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Smoke Control / Dampers' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'mechanical', category_name: 'Mechanical', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Temporary Pole Power' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Underground Work' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Rough' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Rough Walls' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Rough – Fire / Life Safety' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Energy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Electrical Release' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'electrical', category_name: 'Electrical', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Underground Work' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Rough' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Water Heater' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Water Distribution / Re-pipe' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Water Service' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Sewer / Cap' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Shower Pan / Tub' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Gas Test' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Gas Release' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'plumbing', category_name: 'Plumbing', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Alarm' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Sprinkler' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Hood / Suppression' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Damper' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Smoke Control' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Preliminary Final', comments: 'Request when seeking a Temporary Certificate of Occupancy' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'fire', category_name: 'Fire', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'roof', category_name: 'Roof', name: 'Pre-cover / Tear Off' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'roof', category_name: 'Roof', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'roof', category_name: 'Roof', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'window_replacement', category_name: 'Window Replacement', name: 'Framing' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'window_replacement', category_name: 'Window Replacement', name: 'Weatherproofing / Lath' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'window_replacement', category_name: 'Window Replacement', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'window_replacement', category_name: 'Window Replacement', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'block_wall', category_name: 'Block Wall', name: 'Location / Footing /Steel' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'block_wall', category_name: 'Block Wall', name: 'Pre-grout', comments: 'Note lift designation (e.g. mid-height, top course) in comments below, if applicable.' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'block_wall', category_name: 'Block Wall', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'block_wall', category_name: 'Block Wall', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Location / Steel' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Underground Plumbing' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Underground Electrical' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Gas Test' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Pre-gunite' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Fences / Gates' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Health Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Electrical Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Planning Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Mechanical Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'pool', category_name: 'Pool', name: 'Pool Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Array Attachment' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Rough' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Release' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'photovoltaic', category_name: 'Photovoltaic', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'sign', category_name: 'Sign', name: 'Location / Footing / Steel' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'sign', category_name: 'Sign', name: 'Underground Conduit' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'sign', category_name: 'Sign', name: 'Rough' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'sign', category_name: 'Sign', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'sign', category_name: 'Sign', name: 'Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Location / Footing / Steel' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Framing / Attachments' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Rough' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Other', comments: 'Please write in comments section below' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Planning Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Fire Final' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Electrical Release' },
  {supercategory: 'commercial', supercategory_name:'Commercial / Multifamily Residential / Condo', category: 'cell_sites', category_name: 'Cell Sites', name: 'Building Final' },
].each do |it|
  InspectionType.create(
    inspection_supercategory: it[:supercategory],
    inspection_supercategory_name: it[:supercategory_name],
    inspection_category: it[:category],
    inspection_category_name: it[:category_name],
    inspection_name: it[:name],
    comments: it[:comments],
  )
end

Inspection.delete_all

# past
5.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    inspection_notes: 'Test',
    requested_for_date: Faker::Date.backward(30),
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    address_notes: Faker::Lorem.sentence,
  )
end

# yesterday
2.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    inspection_notes: 'Test',
    requested_for_date: Date.yesterday,
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    address_notes: Faker::Lorem.sentence,
  )
end

# today
3.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    inspection_notes: 'Test',
    requested_for_date: Date.today,
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    address_notes: Faker::Lorem.sentence,
  )
end

# tomorrow
4.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    inspection_notes: 'Test',
    requested_for_date: Date.tomorrow,
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    address_notes: Faker::Lorem.sentence,
  )
end

# future
5.times do
  Inspection.create(
    permit_number: '123456',
    contact_name: Faker::Name.name,
    contact_phone: Faker::PhoneNumber.phone_number,
    inspection_type: InspectionType.order('random()').take,
    inspection_notes: 'Test',
    requested_for_date: Faker::Date.forward(30),
    requested_for_time: [nil, 'am','pm'].sample,
    address: Address.create(line_1: "1234 Example Lane", city: "Long Beach", state: 'CA', zip: '12345'),
    address_notes: Faker::Lorem.sentence,
  )
end
